version: '3'
services:
  pymom_register_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-register:latest
    container_name: pymom_register_pro
    hostname: pymom_register_pro
    restart: always
    ports:
      - 6553:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_home_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-home:latest
    container_name: pymom_home_pro
    hostname: pymom_home_pro
    restart: always
    ports:
      - 6550:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_managerdata_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-managerdata:latest
    container_name: pymom_managerdata_pro
    hostname: pymom_managerdata_pro
    restart: always
    ports:
      - 6551:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_managerselect_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-managerselect:latest
    container_name: pymom_managerselect_pro
    hostname: pymom_managerselect_pro
    restart: always
    ports:
      - 6552:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_zuulclient_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-zuulclient:latest
    container_name: pymom_zuulclient_pro
    hostname: pymom_zuulclient_pro
    restart: always
    ports:
      - 6554:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_manager_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-manager:latest
    container_name: pymom_manager_pro
    hostname: pymom_manager_pro
    restart: always
    ports:
      - 6555:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_outsourcehome_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-outsourcehome:latest
    container_name: pymom_outsourcehome_pro
    hostname: pymom_outsourcehome_pro
    restart: always
    ports:
      - 6556:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_position_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-position:latest
    container_name: pymom_position_pro
    hostname: pymom_position_pro
    restart: always
    ports:
      - 6557:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_analysis_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-analysis:latest
    container_name: pymom_analysis_pro
    hostname: pymom_analysis_pro
    restart: always
    ports:
      - 6558:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_benchmark_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-benchmark:latest
    container_name: pymom_benchmark_pro
    hostname: pymom_benchmark_pro
    restart: always
    ports:
      - 6559:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_group_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-group:latest
    container_name: pymom_group_pro
    hostname: pymom_group_pro
    restart: always
    ports:
      - 6560:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_calculate_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-calculate:latest
    container_name: pymom_calculate_pro
    hostname: pymom_calculate_pro
    restart: always
    ports:
      - 6561:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

  pymom_pythonmodule_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-pythonmodule:latest
    container_name: pymom_pythonmodule_pro
    hostname: pymom_pythonmodule_pro
    restart: always
    ports:
      - 6564:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - python
      - -u
      - /python3/manage.py
      - runserver
      - 0.0.0.0:5000
    networks:
      - pro

  pymom_backstage-system_pro:
    image: registry.cn-qingdao.aliyuncs.com/pystandard/pymom-backstage-system:latest
    container_name: pymom_backstage-system_pro
    hostname: pymom_backstage-system_pro
    restart: always
    ports:
      - 6563:5000
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "ss -tnlp|grep -w 5000|grep -v grep"]
      interval: 5s
      timeout: 2s
      retries: 3
    entrypoint:
      - java
      - -Xms128m
      - -Xmx256m
      - -jar
      - /java8/app.jar
      - --server.port=5000
      - --spring.profiles.active=pro
    networks:
      - pro

networks:
  pro:
    external: false
