apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pro.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: k8stest-pymom-managerdata-dev
  name: k8stest-pymom-managerdata-dev
  namespace: k8stest-pymom-dev
spec:
  type: NodePort
  ports:
  - name: "6501"
    port: 6501
    targetPort: 5000
    nodePort: 6501
  selector:
    io.kompose.service: k8stest-pymom-managerdata-dev
status:
  loadBalancer: {}