apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pro.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: k8stest-pymom-managerdata-pro
  name: k8stest-pymom-managerdata-pro
  namespace: k8stest-pymom-pro
spec:
  type: NodePort
  ports:
  - name: "6551"
    port: 6551
    targetPort: 5000
    nodePort: 6551
  selector:
    io.kompose.service: k8stest-pymom-managerdata-pro
status:
  loadBalancer: {}